- hosts: localhost
  tasks:
  - 
    name: install zsh plugin - zsh-syntax-highlighting
    ansible.builtin.git:
      repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
      dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
  - 
    name: install zsh plugin - zsh-autosuggestions
    ansible.builtin.git:
      repo: 'https://github.com/zsh-users/zsh-autosuggestions'
      dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
  - 
    name: install zsh plugin - git-open
    ansible.builtin.git:
      repo: 'https://github.com/paulirish/git-open.git'
      dest: ~/.oh-my-zsh/custom/plugins/git-open
  - 
    name: install zsh plugin - ugit
    ansible.builtin.git:
      repo: 'https://github.com/Bhupesh-V/ugit.git'
      dest: ~/.oh-my-zsh/custom/plugins/ugit
  - 
    name: install zsh plugin - you should use
    ansible.builtin.git:
      repo: 'https://github.com/MichaelAquilina/zsh-you-should-use.git'
      dest: ~/.oh-my-zsh/custom/plugins/you-should-use
  - 
    name: install zsh plugin - fzf-tab
    ansible.builtin.git:
      repo: 'https://github.com/Aloxaf/fzf-tab'
      dest: ~/.oh-my-zsh/custom/plugins/fzf-tab
  - 
    name: install zsh plugin - zsh-aws-vault
    ansible.builtin.git:
      repo: 'https://github.com/blimmer/zsh-aws-vault.git'
      dest: ~/.oh-my-zsh/custom/plugins/zsh-aws-vault
  - 
    name: install - lsd
    community.general.homebrew:
      name: lsd
      path: /home/linuxbrew/.linuxbrew/bin
      state: present
      update_homebrew: yes
  - 
    name: install - bat
    community.general.homebrew:
      name: bat
      path: /home/linuxbrew/.linuxbrew/bin
      state: present
  - 
    name: install - gping
    community.general.homebrew:
      name: orf/brew/gping
      path: /home/linuxbrew/.linuxbrew/bin
      state: present
      update_homebrew: yes
  - 
    name: install - curlie
    community.general.homebrew:
      name: rs/tap/curlie
      path: /home/linuxbrew/.linuxbrew/bin
      state: present
      update_homebrew: yes
  - 
    name: install - less
    community.general.homebrew:
      name: less
      path: /home/linuxbrew/.linuxbrew/bin
      state: latest
      update_homebrew: yes
  - 
    name: install - delta
    community.general.homebrew:
      name: git-delta
      path: /home/linuxbrew/.linuxbrew/bin
      state: present
      update_homebrew: yes
  - 
    name: install - dust
    community.general.homebrew:
      name: dust
      path: /home/linuxbrew/.linuxbrew/bin
      state: present
      update_homebrew: yes
  - 
    name: install - duf
    community.general.homebrew:
      name: duf
      path: /home/linuxbrew/.linuxbrew/bin
      state: present
      update_homebrew: yes
  - 
    name: install - broot
    community.general.homebrew:
      name: broot
      path: /home/linuxbrew/.linuxbrew/bin
      state: present
      update_homebrew: yes
  - 
    name: tab - mcfly
    community.general.homebrew_tap:
      name: cantino/mcfly
      path: /home/linuxbrew/.linuxbrew/bin
  - 
    name: install - mcfly
    community.general.homebrew:
      name: mcfly
      path: /home/linuxbrew/.linuxbrew/bin
      state: present
      update_homebrew: yes
  - 
    name: install - zoxide
    community.general.homebrew:
      name: zoxide
      path: /home/linuxbrew/.linuxbrew/bin
      state: present
      update_homebrew: yes
  - 
    name: install - dog
    community.general.homebrew:
      name: dog
      path: /home/linuxbrew/.linuxbrew/bin
      state: present
      update_homebrew: yes
  - 
    name: install - xh
    community.general.homebrew:
      name: xh
      path: /home/linuxbrew/.linuxbrew/bin
      state: present
      update_homebrew: yes
  -
    name: Create a directory if it does not exist
    ansible.builtin.file:
      path: ~/.config/ansible_setup
      state: directory
  - 
    name: install - forgit
    get_url:
      url: http://git.io/forgit
      dest: ~/.config/ansible_setup/forgit
      mode: u=rw,g=r,o=r
  - 
    name: configure pet in zshrc
    blockinfile:
      path: ~/.zshrc
      marker_begin: PET BEGIN
      marker_end: PET END
      block: |
        function prev() {
          PREV=$(fc -lrn | head -n 1)
          sh -c "pet new `printf %q "$PREV"`"
        }
        function pet-select() {
          BUFFER=$(pet search --query "$LBUFFER")
          CURSOR=$#BUFFER
          zle redisplay
        }
        zle -N pet-select
        stty -ixon
        bindkey '^s' pet-select
      create: yes
  - 
    name: configure pet sync - PAT
    ansible.builtin.lineinfile:
      path: ~/.config/pet/config.toml
      firstmatch: yes
      regexp: '^  access_token = '
      line: "  access_token = \"{{ pet_PAT }}\""
      create: yes
  - 
    name: configure pet sync - gist_id
    ansible.builtin.lineinfile:
      path: ~/.config/pet/config.toml
      firstmatch: yes
      regexp: '^  gist_id = '
      line: "  gist_id = \"{{ pet_gist_id }}\""
      create: yes
  - 
    name: configure pet sync - auto_sync
    ansible.builtin.lineinfile:
      path: ~/.config/pet/config.toml
      firstmatch: yes
      regexp: '^  auto_sync = '
      line: "  auto_sync = true"
      create: yes
  - 
    name: configure zsh theme - agnoster
    ansible.builtin.lineinfile:
      path: ~/.zshrc
      regexp: '^ZSH_THEME='
      line: ZSH_THEME="agnoster"
      create: yes
  - 
    name: configure zsh plugins - git autojump zsh-autosuggestions zsh-syntax-highlighting fzf
    ansible.builtin.lineinfile:
      path: ~/.zshrc
      regexp: '^plugins='
      line: |
        plugins=(git autojump zsh-autosuggestions zsh-syntax-highlighting fzf git-open ugit you-should-use fzf-tab aws zsh-aws-vault)      
      create: 
  - 
    name: configure git
    blockinfile:
      path: ~/.gitconfig
      create: yes
      block: |
        [pager]
            diff = delta
            log = delta
            reflog = delta
            show = delta

        [delta]
            features = side-by-side line-numbers decorations
            syntax-theme = Dracula
            plus-style = syntax "#003800"
            minus-style = syntax "#3f0001"

        [delta "decorations"]
            commit-decoration-style = bold yellow box ul
            file-style = bold yellow ul
            file-decoration-style = none
            hunk-header-decoration-style = cyan box ul

        [delta "line-numbers"]
            line-numbers-left-style = cyan
            line-numbers-right-style = cyan
            line-numbers-minus-style = 124
            line-numbers-plus-style = 28

        [interactive]
            diffFilter = delta --color-only
  - 
    name: configure aliases
    blockinfile:
      path: ~/.zshrc
      block: "{{ lookup('file', '../templates/alias.txt') }}"
  - 
    name: configure prompt
    blockinfile:
      marker_begin: PROMPT BEGIN
      marker_end: PROMPT END
      path: ~/.zshrc
      block: "{{ lookup('file', '../templates/prompt.txt') }}"
