---
- hosts: local
  become: yes
  vars:
    app_name: Docker
    app_url: https://desktop.docker.com/mac/stable/amd64/Docker.dmg
    installer_type: app
    install_method: dmg
    download_file_type: dmg
  roles:
    - setup
    - installer
    - cleanup
   