---
- hosts: local
  become: yes
  vars:
    app_name: Visual Studio Code
    app_url: https://az764295.vo.msecnd.net/stable/f30a9b73e8ffc278e71575118b6bf568f04587c8/VSCode-darwin-universal.zip
    installer_type: app
    install_method: dmg
    download_file_type: zip
  roles:
    - setup
    - installer
    - cleanup