---
- 
  name: install - zsh
  community.general.homebrew:
    name: zsh
    state: present
    update_homebrew: yes
- 
  name: install - curl
  community.general.homebrew:
    name: curl
    state: present
- 
  name: change default shell to zsh
  ansible.builtin.command: chsh -s $(which zsh)
  become: yes
- 
  name: install oh-my-zsh
  ansible.builtin.command: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  become: yes
- 
  name: install zsh plugin - zsh-syntax-highlighting
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
    dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
- 
  name: install zsh plugin - zsh-autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions'
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
- 
  name: install - lsd
  community.general.homebrew:
    name: lsd
    state: present
    update_homebrew: yes
- 
  name: install - bat
  community.general.homebrew:
    name: bat
    state: present
    update_homebrew: yes
- 
  name: install - autojump
  community.general.homebrew:
    name: autojump
    state: present
    update_homebrew: yes
- 
  name: install - fd
  community.general.homebrew:
    name: fd
    state: present
    update_homebrew: yes
- 
  name: install - fzf
  community.general.homebrew:
    name: fzf
    state: present
    update_homebrew: yes
- 
  name: install - pet
  community.general.homebrew:
    name: knqyf263/pet/pet
    state: present
    update_homebrew: yes
- 
  name: configure pet in zshrc
  blockinfile:
    path: ~/.zshrc
    block: |
      function prev() {
        PREV=$(fc -lrn | head -n 1)
        sh -c "pet new `printf %q "$PREV"`"
      }
      function pet-select() {
        BUFFER=$(pet search --query "$LBUFFER")
        CURSOR=$#BUFFER
        zle redisplay
      }
      zle -N pet-select
      stty -ixon
      bindkey '^s' pet-select
- 
  name: configure zsh theme - agnoster
  ansible.builtin.lineinfile:
    path: ~/.zshrc
    regexp: '^ZSH_THEME='
    line: ZSH_THEME="agnoster"
    create: yes
- 
  name: configure zsh plugins - git autojump zsh-autosuggestions zsh-syntax-highlighting fzf
  ansible.builtin.lineinfile:
    path: ~/.zshrc
    regexp: '^plugins='
    line: |
      plugins=(git autojump zsh-autosuggestions zsh-syntax-highlighting fzf)      
    create: 
- 
  name: configure aliases
  blockinfile:
    path: ~/.zshrc
    block: |
      code () { VSCODE_CWD="$PWD" open -n -b "com.microsoft.VSCode" --args $* ;}
      alias k="kubectl"
      alias t="terraform"
      alias ls="lsd --no-symlink"
      alias ll="lsd -l --no-symlink"
      alias lt="lsd --tree --no-symlink"
      alias cat="bat"
      alias gs="git status"
      export FZF_DEFAULT_COMMAND=’fd — type f’
      export MANPAGER="sh -c 'col -bx | bat -l man -p'"